when:
  - event: push
  - event: pull_request

steps:
  - name: check
    image: oven/bun:alpine
    commands:
      - bun install --frozen-lockfile
      - bun run check

  - name: docker
    image: woodpeckerci/plugin-docker-buildx:6.1.1
    privileged: true
    settings:
      dry_run: true
      repo: ghcr.io/wissem-industries/parcourtime
      dockerfile: Dockerfile
    depends_on:
      - check
