when:
  - event: [push, pull_request, tag]

steps:
  - name: check
    image: oven/bun:alpine
    commands:
      - bun install --frozen-lockfile
      - bun run check

  - name: container-dry-run
    image: woodpeckerci/plugin-kaniko:2.3.2
    settings:
      dry-run: true
      repo: wissem-industries/parcourtime
      dockerfile: Dockerfile
      tags:
        - ${CI_COMMIT_SHA}
    depends_on:
      - check
    when:
      - event: [push, pull_request]
